### ISSUE TITLE
"Open Advanced Settings for More Options" crashes launcher

### ISSUE THREAD

**Issue by DevanWolf** [threethan/LightningLauncher#167]
```
FATAL EXCEPTION: main
Process: com.threethan.launcher, PID: 26066
java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
       at java.util.Arrays$ArrayList.get(Arrays.java:3766)
       at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:394)
       at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:450)
       at android.widget.ArrayAdapter.getView(ArrayAdapter.java:416)
       at android.widget.Spinner.makeView(Spinner.java:724)
       at android.widget.Spinner.layout(Spinner.java:672)
       at android.widget.Spinner.onLayout(Spinner.java:634)
       at android.view.View.layout(View.java:23203)
       at android.view.ViewGroup.layout(ViewGroup.java:6412)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
       at android.view.View.layout(View.java:23203)
       at android.view.ViewGroup.layout(ViewGroup.java:6412)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23203)
       at android.view.ViewGroup.layout(ViewGroup.java:6412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.widget.ScrollView.onLayout(ScrollView.java:1689)
       at android.view.View.layout(View.java:23203)
       at android.view.ViewGroup.layout(ViewGroup.java:6412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23203)
       at android.view.ViewGroup.layout(ViewGroup.java:6412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23203)
       at android.view.ViewGroup.layout(ViewGroup.java:6412)
       at com.android.internal.widget.AlertDialogLayout.setChildFrame(AlertDialogLayout.java:358)
       at com.android.internal.widget.AlertDialogLayout.onLayout(AlertDialogLayout.java:351)
       at android.view.View.layout(View.java:23203)
       at android.view.ViewGroup.layout(ViewGroup.java:6412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23203)
       at android.view.ViewGroup.layout(ViewGroup.java:6412)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23203)
       at android.view.ViewGroup.layout(ViewGroup.java:6412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:797)
       at android.view.View.layout(View.java:23203)
       at android.view.ViewGroup.layout(ViewGroup.java:6412)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3809)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3259)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2224)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8893)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
       at android.view.Choreographer.doCallbacks(Choreographer.java:845)
       at android.view.Choreographer.doFrame(Choreographer.java:780)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:214)
       at android.os.Looper.loop(Looper.java:304)
       at android.app.ActivityThread.main(ActivityThread.java:7918)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1010)
```
This bug did not happen prior to 8.0.0

**Comment by threethan** [comment]
This came from carrying over a config value from an older version.

Should be resolved in 8.1. If not, let me know and I'll reopen the issue.
